
version: 2

sources:
  - name: commodities
    schema: commodities
    tables: 
      
      - name: commodities
        description: "Tabela que contém dados históricos de commodities"
        columns:
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço de fechamento da commoditie"
          - name: Close
            description: "Símbolo da commoditie"
      
      - name: movimentacao_commodities
        description: "Tabela seed"
        columns:
          - name: date
            description: "Data da transação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo de transação"
          - name: quantity
            description: "Quantidade transancionada"

              